name: hori_hori
description: A Swiss Army knife for versioning and releasing Flutter-based software.
version: 1.0.0

dependencies:
  args: ^1.6.0
  pub_semver: ^1.4.4

dev_dependencies:
  test: ^1.6.3
